#!/bin/sh

set -e

SIGIL_LIB_DIR=/var/lib/sigil
SIGIL_USER="sigil"
SIGIL_GROUP="sigil"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    remove)
        deluser --quiet --system $SIGIL_USER || true
        delgroup --quiet --system --only-if-empty $SIGIL_GROUP || true
        	# remove workaround for https://bugs.debian.org/1059326
        if [ -L ${GSFONTS_DIR}/n021003l.pfb ] ; then
            rm ${GSFONTS_DIR}/n021003l.pfb
            if [ "$(ls -A ${GSFONTS_DIR})" = ".created-by-sigil-package" ] ; then
                rm -fr ${GSFONTS_DIR}
            fi
    	fi
        ;;

    purge)
        if [ -d "$SIGIL_LIB_DIR" ]; then
            rm -rf $SIGIL_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
