import logging
import json
import tempfile
import shutil

from pathlib import Path

from sigil import _, api, fields, models
from sigil.exceptions import UserError
from sigil.addons.karaoke_iantirta import utils as karaoke_utils

_logger = logging.getLogger(__name__)


class GpuWorker(models.Model):
    _name = 'gpu.worker'
    _description = 'GPU Worker'

    name = fields.Char(required=True)

    provider = fields.Selection([
        ("kaggle", "Kaggle")
    ], required=True)

    access_token = fields.Char(
        string="Kaggle API Token", required=True,
        help='https://www.kaggle.com/settings/api (click "Generate New Token" under "API")'
    )

    quota_json = fields.Json(compute="_compute_quotas", store=True)

    # Helper
    _worker = None

    def _get_worker_class(self):
        from .kplus_tools import KaggleWorker
        provider_map = {
            "kaggle": KaggleWorker
        }
        return provider_map.get(self.provider, None)

    def _get_worker_instance(self):
        self.ensure_one()
        if instance := self._get_worker_class():
            return instance(self.access_token)
        raise UserError(_("Unsupported provider configuration."))
    
    # Quotas
    def get_quotas(self) -> dict:
        quotas = self._get_worker_instance().get_quota()
        self.quota_json = quotas
        return quotas

    @api.depends("access_token", 'name', "provider")
    def _compute_quotas(self):
        for record in self:
            if record.access_token:
                try:
                    record.get_quotas()
                except Exception as e:
                    _logger.error("Failed to fetch quotas for %s: %s", record.name, e)
                    record.quota_json = {
                        "error": "Failed to fetch quotas",
                        "error_str": str(e),
                    }
            else:
                record.quota_json = {}

    def action_get_quotas(self):
        return self.get_quotas()

    # Running
    def action_run(self):
        worker = self._get_worker_instance()

        script_folder = Path(__file__).resolve().parent / "notebook"
        script_path = script_folder / "worker.ipynb"

        with open(str(script_path), "r") as f:
            notebook = json.load(f)

        # it should be the first cell
        if (
            len(notebook["cells"]) > 1 and
            (env_cell := notebook["cells"][0])["cell_type"] == "code" and
            "Do Not Modified" in env_cell["source"][0]
        ):
            new_access_token = karaoke_utils.generate_access_token(
                self.name, self.provider
            )

            base_url = self.env["ir.config_parameter"].get("web.base.url")

            env_cell["source"]
            env_cell["source"] = [
                "# Do Not Modified. Generated by iantirta.com\n",
                "import os\n",
                f'iantirta_url = "{base_url}"\n'
                f"os.environ['IANTIRTA_API_KEY'] = '{new_access_token}'\n",
                f'worker_name = "{self.name}"\n',
                f'worker_provider = "{self.provider}"\n',
            ]
        else:
            raise RuntimeError("Unknown template of worker.ipynb")

        with tempfile.TemporaryDirectory() as tmpdir:
            tmp_script_path = Path(tmpdir) / "worker.ipynb"

            with open(str(tmp_script_path), "w") as f:
                json.dump(notebook, f, indent=1)

            if self.provider == "kaggle":
                metadata_path = script_folder / "kernel-metadata.json"
                tmp_metadata_path = Path(tmpdir) / "kernel-metadata.json"
                shutil.copy(metadata_path, tmp_metadata_path)

            # if kaggle it is a folder
            # if colab it is a file
            folder = tmpdir
            if self.provider == "colab":
                folder = tmp_script_path

            response = worker.run(str(folder))
