
from . import (
    assetsbundle,  # noqa: F401
    avatar_mixin,  # noqa: F401
    decimal_precision,  # noqa: F401
    image_mixin,  # noqa: F401
    ir_actions,  # noqa: F401
    ir_actions_report,  # noqa: F401
    ir_asset,  # noqa: F401
    ir_attachment,  # noqa: F401
    ir_autovacuum,  # noqa: F401
    ir_binary,  # noqa: F401
    ir_config_parameter,  # noqa: F401
    ir_cron,  # noqa: F401
    ir_default,  # noqa: F401
    ir_demo,  # noqa: F401
    ir_demo_failure,  # noqa: F401
    ir_embedded_actions,  # noqa: F401
    ir_exports,  # noqa: F401
    ir_fields,  # noqa: F401
    ir_filters,  # noqa: F401
    ir_http,  # noqa: F401
    ir_logging,  # noqa: F401
    ir_mail_server,  # noqa: F401
    ir_model,  # noqa: F401
    ir_module,  # noqa: F401
    ir_profile,  # noqa: F401
    ir_qweb,  # noqa: F401
    ir_qweb_fields,  # noqa: F401
    ir_rule,  # noqa: F401
    ir_sequence,  # noqa: F401
    ir_ui_menu,  # noqa: F401
    ir_ui_view,  # noqa: F401
    properties_base_definition,  # noqa: F401
    properties_base_definition_mixin,  # noqa: F401
    report_layout,  # noqa: F401
    report_paperformat,  # noqa: F401
    res_bank,  # noqa: F401
    res_company,  # noqa: F401
    res_config,  # noqa: F401
    res_country,  # noqa: F401
    res_currency,  # noqa: F401
    res_device,  # noqa: F401
    res_groups,  # noqa: F401
    res_groups_privilege,  # noqa: F401
    res_lang,  # noqa: F401
    res_partner,  # noqa: F401
    res_users,  # noqa: F401
    res_users_deletion,  # noqa: F401
    res_users_settings,  # noqa: F401
)
